/*
 * Main.java
 *
 * Created on 19. April 2005, 19:10
 */

package de.jflyingcubes.player;

import de.jflyingcubes.player.cubes.Button;
import de.jflyingcubes.player.cubes.plugins.MoveFactory;
import de.jflyingcubes.player.cubes.plugins.MovePlugin;
import de.jflyingcubes.player.io.Parser;
import de.jflyingcubes.player.page.Pages;
import de.jflyingcubes.player.util.Screen;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import de.jflyingcubes.player.cubes.Image;
import de.jflyingcubes.player.cubes.CubesCollection;
import de.jflyingcubes.player.cubes.Cubes;

/**
 *
 * @author  dm
 */
public class Main extends javax.swing.JFrame {
    
    private final Pages pages = new Pages();
    private final ViewerPanel viewer = new ViewerPanel(pages);
    /** Creates new form Main */
    public Main() {
        initComponents();
        Dimension dim = Screen.getScreenSize();
        setSize(dim);
        add(viewer, BorderLayout.CENTER);
    }

    public void load(String[] args) throws FileNotFoundException {
        InputStream is = null;
        if (args.length > 0 && args[0].trim().length() > 0)
            is = new FileInputStream(args[0]);
        else
            is = getClass().getResourceAsStream("/de/jflyingcubes/player/io/example.xml");
        
        if (is == null)
            usage();
        Parser.parse(pages, is);
    }
    
    public void start() {
        viewer.start();
    }
    private void usage() {
        System.out.println("usage :");
        System.exit(1);
    }
    
//    public void initElements() {
//        elements.addElement(new Element(0, 0, 10, 10, Color.RED));
//        elements.addElement(new Element(30, 30, 50, 50, Color.BLUE, Color.RED, 10));
//        final MovePlugin plugin = new MovePlugin(MoveFactory.getMoveDatas(-100, -100, 300, 300, 4));
//        elements.addElement(new AnimatedImageElement(100, plugin, getImageIcon("/p4b_big.jpg"), 100, 100));
//        MovePlugin plugin1 = new MovePlugin(MoveFactory.getMoveDatas(0, 0, 200, 300));
//        elements.addElement(new AnimatedElement(100, plugin1));
//        ButtonElement button1 = new ButtonElement("press me", 150, 100);
//        button1.addActionListener(new ActionListener() {
//            public void actionPerformed(ActionEvent evt) {
//System.out.println("button clicked");
//                plugin.restart();
//            }
//        });
//        elements.addElement(button1);
//    }
    
//    public ImageIcon getImageIcon(String name) {
//        return new ImageIcon(getClass().getResource(name));
//    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        popupMenu = new javax.swing.JPopupMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        setBounds(0, 0, 400, 300);
    }//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            System.exit(0);
    }//GEN-LAST:event_formKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Main main = new Main();
        main.setVisible(true);
        try {
            main.load(args);
            main.start();
        } catch (FileNotFoundException e) {
            System.out.println("File not found....");
            System.exit(1);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
    
    private class InsertAction extends AbstractAction {
        public InsertAction() {
            super("insert");
        }
        
        public void actionPerformed(ActionEvent evt) {
//            jDesktopPane1.add(new Element());
        }
    }
    
    
    
}
